/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.research.llmbattery;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int accent_color=0x7f060002;
        public static final int background_color=0x7f060003;
        public static final int battery_high=0x7f060008;
        /**  Status colors 
         */
        public static final int battery_low=0x7f060006;
        public static final int battery_medium=0x7f060007;
        public static final int black=0x7f06000a;
        /**  Basic colors for the app 
         */
        public static final int primary_color=0x7f060000;
        public static final int primary_dark_color=0x7f060001;
        public static final int text_primary=0x7f060004;
        public static final int text_secondary=0x7f060005;
        /**  Common colors 
         */
        public static final int white=0x7f060009;
    }
    public static final class drawable {
        public static final int button_primary=0x7f020000;
        public static final int button_secondary=0x7f020001;
        public static final int card_background=0x7f020002;
        public static final int ic_export=0x7f020003;
        public static final int ic_model=0x7f020004;
        public static final int ic_play=0x7f020005;
        public static final int ic_timer=0x7f020006;
    }
    public static final class id {
        public static final int btn_export=0x7f090008;
        public static final int btn_start_stop=0x7f090007;
        public static final int progress_bar=0x7f090006;
        public static final int spinner_interval=0x7f090001;
        public static final int spinner_model=0x7f090000;
        public static final int tv_avg_inference_time=0x7f090004;
        public static final int tv_battery_level=0x7f090002;
        public static final int tv_est_battery_life=0x7f090005;
        public static final int tv_queries_completed=0x7f090003;
    }
    public static final class layout {
        public static final int activity_main=0x7f040000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
        public static final int ic_launcher_round=0x7f030001;
    }
    public static final class string {
        public static final int app_description=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int avg_inference_time=0x7f07000b;
        public static final int battery_level=0x7f070009;
        public static final int benchmark_completed=0x7f070014;
        public static final int benchmark_configuration=0x7f070004;
        /**  Status messages 
         */
        public static final int benchmark_started=0x7f070012;
        public static final int benchmark_stopped=0x7f070013;
        public static final int cancel=0x7f070023;
        /**  Accessibility 
         */
        public static final int content_description_battery_icon=0x7f07003f;
        public static final int content_description_export_button=0x7f070041;
        public static final int content_description_interval_spinner=0x7f070043;
        public static final int content_description_model_spinner=0x7f070042;
        public static final int content_description_progress_bar=0x7f070040;
        public static final int error_exporting_results=0x7f07001f;
        public static final int error_loading_models=0x7f07001c;
        /**  Error messages 
         */
        public static final int error_select_model=0x7f07001b;
        public static final int error_starting_benchmark=0x7f07001d;
        public static final int error_stopping_benchmark=0x7f07001e;
        public static final int estimated_battery_life=0x7f07000c;
        public static final int export_description=0x7f07000f;
        public static final int export_failed=0x7f070018;
        public static final int export_results=0x7f07000e;
        public static final int export_success_message=0x7f070025;
        public static final int export_success_title=0x7f070024;
        public static final int export_successful=0x7f070017;
        public static final int go_to_settings=0x7f07002c;
        public static final int grant_permission=0x7f07002b;
        /**  Interval options 
         */
        public static final int interval_1_minute=0x7f070010;
        public static final int interval_5_minutes=0x7f070011;
        public static final int model_load_failed=0x7f070016;
        public static final int model_loaded=0x7f070015;
        /**  Model information 
         */
        public static final int model_quantization_2bit=0x7f070033;
        public static final int model_quantization_3bit=0x7f070034;
        public static final int model_quantization_4bit=0x7f070035;
        public static final int model_quantization_5bit=0x7f070036;
        public static final int model_quantization_6bit=0x7f070037;
        public static final int model_quantization_8bit=0x7f070038;
        public static final int model_quantization_fp16=0x7f070039;
        public static final int model_quantization_fp32=0x7f07003a;
        /**  MainActivity strings 
         */
        public static final int model_selection=0x7f070002;
        /**  Notification messages 
         */
        public static final int notification_benchmark_running=0x7f07003b;
        public static final int notification_benchmark_running_content=0x7f07003c;
        public static final int notification_export_complete=0x7f07003d;
        public static final int notification_export_complete_content=0x7f07003e;
        public static final int ok=0x7f070026;
        public static final int permission_battery_message=0x7f07002a;
        public static final int permission_battery_title=0x7f070029;
        public static final int permission_storage_message=0x7f070028;
        /**  Permission messages 
         */
        public static final int permission_storage_title=0x7f070027;
        public static final int permissions_denied=0x7f07001a;
        public static final int permissions_granted=0x7f070019;
        public static final int queries_completed=0x7f07000a;
        public static final int query_interval=0x7f070005;
        public static final int real_time_metrics=0x7f070008;
        public static final int results_export=0x7f07000d;
        public static final int select_model=0x7f070003;
        public static final int start_benchmark=0x7f070006;
        public static final int stop=0x7f070022;
        public static final int stop_benchmark=0x7f070007;
        public static final int stop_benchmark_message=0x7f070021;
        /**  Dialog messages 
         */
        public static final int stop_benchmark_title=0x7f070020;
        public static final int unit_gigabytes=0x7f070032;
        public static final int unit_hours=0x7f070030;
        public static final int unit_megabytes=0x7f070031;
        public static final int unit_milliseconds=0x7f07002e;
        public static final int unit_minutes=0x7f07002f;
        /**  Units 
         */
        public static final int unit_percent=0x7f07002d;
    }
    public static final class style {
        /**  Base application theme 
         */
        public static final int Theme_LLMBatteryBenchmark=0x7f080000;
    }
    public static final class xml {
        public static final int backup_rules=0x7f050000;
        public static final int data_extraction_rules=0x7f050001;
        public static final int file_paths=0x7f050002;
    }
}
